version: '2.1'
services:
  repositoryserver:
    image: docker.home.jm0.eu/obs/repositoryserver
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    ports:
     - 5252:5252

  sourceserver:
    image: docker.home.jm0.eu/obs/sourceserver
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    ports:
     - 5352:5352
    mem_limit: 10G
    restart: on-failure

  scheduler_local:
    image: docker.home.jm0.eu/obs/scheduler
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    command: local

  scheduler_x86:
    image: docker.home.jm0.eu/obs/scheduler
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs

  scheduler_arm64:
    image: docker.home.jm0.eu/obs/scheduler
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    command: aarch64

  scheduler_armhf:
    image: docker.home.jm0.eu/obs/scheduler
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    command: armv7l

  dodup:
    image: docker.home.jm0.eu/obs/dodup
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs

  signd:
    image: docker.home.jm0.eu/obs/signd
    environment:
     - GNUPGHOME=/srv/obs/gnupg
    volumes:
     - /srv/obs:/srv/obs
    ports:
     - 5167:5167

  signer:
    image: docker.home.jm0.eu/obs/signer
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs

  publisher:
    image: docker.home.jm0.eu/obs/publisher
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    cap_add:
     - SETUID

  dispatcher:
    image: docker.home.jm0.eu/obs/dispatch
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs

  service:
    image: docker.home.jm0.eu/obs/serviceservice
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs
    ports:
     - 5152:5152

  servicedispatch:
    image: docker.home.jm0.eu/obs/servicedispatch
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs

  admin:
    image: docker.home.jm0.eu/obs/admin
    volumes:
     - ./BSConfig.pm:/usr/lib/obs/server/BSConfig.pm
     - /srv/obs:/srv/obs

  worker_1:
    image: docker.home.jm0.eu/obs/worker
    cap_add:
     - SYS_ADMIN
    environment:
     - OBS_WORKER_ID=worker:0
     - OBS_WORKER_JOBS=4
     - OBS_WORKER_PORT=1600
     - OBS_REPO_SERVER=repositoryserver:5252
     - OBS_SRC_SERVER=sourceserver:5352
    ports:
     - 1600:1600
    volumes:
     - /tmp/worker:/var/obsworker/run
