ARG PREFIX=obs/ TAG=:latest
FROM ${PREFIX}base:${TAG}

# install additional runtime dependencies
RUN zypper -n install obs-signd

# import configuration file
COPY sign.conf /etc/

# entrypoint
ENTRYPOINT ["/usr/lib/obs/server/bs_srcserver"]
CMD ["--logfile", "/srv/obs/log/src_server.log"]

# public services on the network
EXPOSE 5352
