ARG PREFIX=obs/
ARG TAG=:latest
FROM ${PREFIX}base:${TAG}

# install additional runtime dependencies
RUN zypper -n install obs-signd openssl

# import configuration file
COPY sign.conf /etc/

# entrypoint
ENTRYPOINT ["/usr/sbin/signd"]
CMD []
