ARG PREFIX=obs/
ARG TAG=:latest
FROM ${PREFIX}base:${TAG}

# install additional runtime dependencies
RUN zypper -n install dpkg gzip obs-signd

# import configuration file
COPY sign.conf /etc/

# entrypoint
ENTRYPOINT ["/usr/lib/obs/server/bs_publish"]
CMD ["--logfile", "/srv/obs/log/publisher.log"]
