ARG PREFIX=obs/
ARG TAG=:latest
FROM ${PREFIX}base:${TAG}

# install additional runtime dependencies
RUN zypper -n install obs-signd

# import configuration file
COPY sign.conf /etc/

# entrypoint
ENTRYPOINT ["/usr/lib/obs/server/bs_signer"]
CMD ["--logfile", "/srv/obs/log/signer.log"]
